version: '3.8'

services:
  pnrsh:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pnrsh
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pnrsh-network

networks:
  pnrsh-network:
    driver: bridge
